name: LevelGuard
version: 1.0.2
main: me.dtmpanda.levelguard.LevelGuardPlugin
api-version: '1.20'

author: Level Check Studios
website: https://levelcheckstudios.com

depend:
  - LevelCore

commands:
  levelguard:
    aliases: [lg]
    description: Main LevelGuard command

permissions:

  levelguard.use:
    default: true

  levelguard.admin:
    default: op

  levelguard.bypass:
    default: op